# Project-wide Gradle settings.
android.useAndroidX=true
android.enableJetifier=true
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false

# Memory and Access Fixes
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dorg.sqlite.tmpdir=C:/temp/gradle_sqlite
org.gradle.parallel=false
kapt.incremental.apt=false
kapt.use.worker.api=false
kotlin.daemon.jvmargs=-Xmx2048m
